clients:
  users:
    base-url: "http://localhost:8081"
    connection-timeout: 5000
    socket-timeout: 5000
  places:
    base-url: "http://localhost:8082"
    connection-timeout: 5000
    socket-timeout: 5000

logging:
  level:
    org.springframework.security: DEBUG